const recipes = [
  [1, "基础鸡肉猫饭", "recipe-01-v021.jpg", "基础", "简单", 20, ["成年猫"], [["鸡胸肉", "80g"], ["鸡心", "10g"], ["鸡肝", "5g"], ["熟蛋黄", "1/2个"]], ["高蛋白", "基础入门"], "适合入门尝试，不建议长期只喂这一种配方。", ["鸡肉", "基础", "高蛋白"]],
  [2, "三文鱼美毛猫饭", "recipe-02-small.jpg", "美毛", "简单", 25, ["成年猫", "换毛期猫"], [["三文鱼", "70g"], ["鸡胸肉", "30g"], ["熟蛋黄", "1/2个"]], ["Omega-3", "美毛"], "鱼类不建议长期大量喂食，注意彻底去刺并避免生食。", ["三文鱼", "美毛", "鱼肉"]],
  [3, "幼猫成长猫饭", "recipe-03-small.jpg", "幼猫", "普通", 25, ["幼猫"], [["鸡腿肉", "80g"], ["鸡心", "10g"], ["熟蛋黄", "1/2个"]], ["高能量", "成长支持"], "幼猫营养要求更高，长期主食需要咨询宠物医生。", ["幼猫", "成长", "鸡腿肉"]],
  [4, "低脂鸡胸猫饭", "recipe-04-small.jpg", "减脂", "简单", 20, ["肥胖猫", "成年猫"], [["鸡胸肉", "100g"], ["南瓜", "10g"]], ["低脂", "易消化"], "减重需要控制总热量，不要只靠更换配方。", ["鸡胸肉", "减脂", "低脂"]],
  [5, "鸭肉低敏猫饭", "recipe-05-v021.jpg", "低敏", "普通", 30, ["疑似敏感猫"], [["鸭胸肉", "90g"], ["南瓜泥", "10g"]], ["单一肉源", "低敏尝试"], "过敏排查应遵医嘱，避免同时混入太多新食材。", ["鸭肉", "低敏", "单一肉源"]],
  [6, "牛肉高蛋白猫饭", "recipe-06-small.jpg", "基础", "普通", 25, ["成年猫"], [["瘦牛肉", "80g"], ["鸡心", "10g"], ["鸡肝", "5g"]], ["高蛋白", "铁元素"], "牛肉适口性好，但脂肪较高的部位不适合频繁喂。", ["牛肉", "高蛋白", "基础"]],
  [7, "鸡肉南瓜肠胃猫饭", "recipe-07-small.jpg", "肠胃", "简单", 25, ["肠胃敏感猫"], [["鸡胸肉", "80g"], ["南瓜", "15g"], ["鸡心", "5g"]], ["温和", "纤维补充"], "腹泻、呕吐持续时应先就医，不要自行长期调整饮食。", ["肠胃", "南瓜", "鸡肉"]],
  [8, "火鸡肉清爽猫饭", "recipe-08-small.jpg", "低敏", "普通", 25, ["成年猫", "敏感猫"], [["火鸡胸肉", "90g"], ["蛋黄", "1/3个"]], ["低脂", "单一主肉源"], "首次尝试新肉源要少量喂，观察皮肤和肠胃反应。", ["火鸡", "低敏", "低脂"]],
  [9, "兔肉温和猫饭", "recipe-09-small.jpg", "低敏", "普通", 30, ["敏感猫", "成年猫"], [["兔肉", "90g"], ["鸡心", "8g"]], ["温和", "低脂"], "兔肉较瘦，长期喂食仍需完整营养配比。", ["兔肉", "低脂", "温和"]],
  [10, "鸡肉蛋黄增肥猫饭", "recipe-10-v021.jpg", "增肥", "简单", 25, ["偏瘦成年猫"], [["鸡腿肉", "85g"], ["鸡心", "10g"], ["熟蛋黄", "1个"]], ["能量较高", "适口性好"], "增重也要循序渐进，突然增加喂食量容易引起肠胃不适。", ["增肥", "蛋黄", "鸡腿肉"]],
  [11, "白鱼轻食猫饭", "recipe-11-v021.jpg", "减脂", "简单", 20, ["成年猫", "需要清淡饮食的猫"], [["白鱼肉", "80g"], ["鸡胸肉", "20g"]], ["清淡", "低脂"], "鱼刺必须清理干净，鱼类配方不建议每天长期喂。", ["白鱼", "清淡", "减脂"]],
  [12, "鸡肝少量营养猫饭", "recipe-12-small.jpg", "基础", "普通", 25, ["成年猫"], [["鸡胸肉", "85g"], ["鸡肝", "5g"], ["鸡心", "10g"]], ["维生素A", "高蛋白"], "肝脏只能少量使用，过量可能造成营养风险。", ["鸡肝", "鸡肉", "基础"]],
  [13, "鳕鱼美毛猫饭", "recipe-13-v021.jpg", "美毛", "普通", 25, ["成年猫"], [["鳕鱼", "70g"], ["鸡胸肉", "30g"]], ["鱼油支持", "适口性高"], "鱼油应按剂量添加，过量可能导致软便。", ["鳕鱼", "美毛", "鱼油"]],
  [14, "羊肉暖胃猫饭", "recipe-14-small.jpg", "增肥", "普通", 30, ["偏瘦成年猫"], [["瘦羊肉", "80g"], ["鸡心", "10g"]], ["能量较高", "适口性强"], "羊肉气味重且脂肪可能偏高，初次喂食要少量。", ["羊肉", "增肥", "高能量"]],
  [15, "鸡肉胡萝卜猫饭", "recipe-15-v021.jpg", "基础", "简单", 25, ["成年猫"], [["鸡胸肉", "90g"], ["熟胡萝卜", "5g"], ["鸡心", "5g"]], ["基础均衡", "少量蔬菜"], "猫是肉食动物，蔬菜只能少量辅助，不要喧宾夺主。", ["鸡肉", "胡萝卜", "基础"]],
  [16, "牛肉鸡心活力猫饭", "recipe-16-v021.jpg", "增肥", "普通", 25, ["活跃成年猫"], [["瘦牛肉", "75g"], ["鸡心", "15g"], ["熟蛋黄", "1/2个"]], ["高蛋白", "能量补充"], "运动量低的猫不要频繁喂高能量配方。", ["牛肉", "鸡心", "增肥"]],
  [17, "鸡肉益生菌肠胃猫饭", "recipe-17-v021.jpg", "肠胃", "简单", 20, ["肠胃敏感猫"], [["鸡胸肉", "90g"], ["南瓜泥", "10g"]], ["易消化", "肠胃支持"], "益生菌不要加入过热食物里，具体用量看产品说明。", ["肠胃", "益生菌", "鸡肉"]],
  [18, "鸭肉南瓜低敏猫饭", "recipe-18-v021.jpg", "低敏", "普通", 30, ["敏感猫"], [["鸭胸肉", "85g"], ["南瓜", "10g"], ["鸡心", "5g"]], ["低敏", "适口性好"], "如果已知对禽类过敏，应避免鸭肉并咨询医生。", ["鸭肉", "南瓜", "低敏"]],
  [19, "鸡肉虾仁尝鲜猫饭", "recipe-19-v021.jpg", "美毛", "普通", 25, ["成年猫"], [["鸡胸肉", "80g"], ["虾仁", "15g"]], ["高蛋白", "适口性高"], "海鲜要少量尝试，出现软便或瘙痒应停止。", ["虾仁", "鸡肉", "尝鲜"]],
  [20, "鸡肉兔肉混合猫饭", "recipe-20-v021.jpg", "基础", "普通", 30, ["成年猫"], [["鸡胸肉", "50g"], ["兔肉", "40g"], ["鸡心", "10g"]], ["多肉源", "高蛋白"], "多肉源适合已确认不过敏的猫，敏感猫建议先从单一肉源开始。", ["鸡肉", "兔肉", "基础"]],
].map(([id, name, cover, category, difficulty, cookTime, suitableFor, ingredients, nutritionFeatures, notes, tags]) => ({ id, name, cover, category, difficulty, cookTime, suitableFor, ingredients: ingredients.map(([name, amount]) => ({ name, amount })), steps: ["清洗并处理食材", "彻底蒸熟或煮熟", "切成小块或细碎状", "放凉后加入营养补充剂拌匀"], supplements: ["牛磺酸", "钙粉"], nutritionFeatures, notes, tags }));
const state = { category: "全部", query: "", favoriteOnly: false };
const FAVORITE_STORAGE_KEY = "catcookFavoriteRecipeIds";
const favoriteRecipeIds = new Set(readFavoriteRecipeIds());
const recipeGrid = document.querySelector("#recipeGrid"), emptyState = document.querySelector("#emptyState"), resultCount = document.querySelector("#resultCount"), searchInput = document.querySelector("#searchInput"), categoryFilterButtons = document.querySelectorAll("[data-category]"), favoriteFilter = document.querySelector("#favoriteFilter"), dailyRecommendation = document.querySelector("#dailyRecommendation"), disclaimerToggle = document.querySelector("#disclaimerToggle"), disclaimerFullText = document.querySelector("#disclaimerFullText"), modal = document.querySelector("#recipeModal"), modalContent = document.querySelector("#modalContent");
function readFavoriteRecipeIds() { try { return JSON.parse(localStorage.getItem(FAVORITE_STORAGE_KEY)) || []; } catch { return []; } }
function saveFavoriteRecipeIds() { localStorage.setItem(FAVORITE_STORAGE_KEY, JSON.stringify([...favoriteRecipeIds])); }
function normalizeText(value) { return String(value).trim().toLowerCase(); }
function recipeSearchText(recipe) { return [recipe.name, recipe.category, recipe.difficulty, recipe.suitableFor.join(" "), recipe.ingredients.map((item) => item.name).join(" "), recipe.tags.join(" "), recipe.nutritionFeatures.join(" ")].join(" "); }
function getVisibleRecipes() { const query = normalizeText(state.query); return recipes.filter((recipe) => (state.category === "全部" || recipe.category === state.category) && (!query || normalizeText(recipeSearchText(recipe)).includes(query)) && (!state.favoriteOnly || favoriteRecipeIds.has(recipe.id))); }
function createTags(items) { return items.map((item) => `<span class="tag">${item}</span>`).join(""); }
function createRecipeImage(recipe, className = "recipe-image") { return `<img class="${className}" src="${recipe.cover}" alt="${recipe.name}成品图" loading="lazy" />`; }
function renderRecipes() { const visibleRecipes = getVisibleRecipes(); resultCount.textContent = `找到 ${visibleRecipes.length} 个猫饭配方`; emptyState.hidden = visibleRecipes.length > 0; recipeGrid.innerHTML = visibleRecipes.map((recipe) => { const isFavorite = favoriteRecipeIds.has(recipe.id); return `<article class="recipe-card" data-card-recipe-id="${recipe.id}" style="cursor: pointer;">${createRecipeImage(recipe)}<div class="card-top"><div class="card-title-group"><h2>${recipe.name}</h2></div><div class="card-actions"><button class="favorite-button ${isFavorite ? "is-favorite" : ""}" type="button" data-favorite-id="${recipe.id}" aria-label="${isFavorite ? "取消收藏" : "收藏"}${recipe.name}" aria-pressed="${isFavorite}">${isFavorite ? "♥" : "♡"}</button><span class="category-pill">${recipe.category}</span></div></div><ul class="meta-list"><li><strong>难度：</strong>${recipe.difficulty}</li><li><strong>制作时间：</strong>${recipe.cookTime} 分钟</li><li><strong>适合：</strong>${recipe.suitableFor.join("、")}</li></ul><div class="tag-list">${createTags(recipe.tags)}</div><button class="detail-button" type="button" data-recipe-id="${recipe.id}">查看详情</button></article>`; }).join(""); }
function renderDailyRecommendation() { const recipe = recipes[Math.floor(Math.random() * recipes.length)]; dailyRecommendation.innerHTML = `${createRecipeImage(recipe, "recommendation-image").replace("<img", `<img data-recommend-id="${recipe.id}"`)}<div class="recommendation-copy"><p class="recommendation-label">今日推荐</p><h2 class="recommendation-title" data-recommend-id="${recipe.id}">${recipe.name}</h2><p class="recommendation-summary">${recipe.notes}</p><div class="recommendation-meta"><span class="category-pill">${recipe.category}</span><span class="tag">${recipe.cookTime} 分钟</span><span class="tag">${recipe.difficulty}</span></div></div><button class="recommendation-button" type="button" data-recommend-id="${recipe.id}">查看推荐</button>`; }
function renderModal(recipe) { modalContent.innerHTML = `<div class="modal-body">${createRecipeImage(recipe, "modal-image")}<h2 id="modalTitle">${recipe.name}</h2><div class="modal-meta"><span class="category-pill">${recipe.category}</span><span class="tag">${recipe.difficulty}</span><span class="tag">${recipe.cookTime} 分钟</span><span class="tag">${recipe.suitableFor.join("、")}</span></div><section class="modal-section"><h3>食材清单</h3><ul class="ingredient-list">${recipe.ingredients.map((item) => `<li>${item.name}：${item.amount}</li>`).join("")}</ul></section><section class="modal-section"><h3>制作步骤</h3><ol class="step-list">${recipe.steps.map((step) => `<li>${step}</li>`).join("")}</ol></section><section class="modal-section"><h3>营养补充</h3><div class="tag-list">${createTags(recipe.supplements)}</div></section><section class="modal-section"><h3>营养特点</h3><div class="tag-list">${createTags(recipe.nutritionFeatures)}</div></section><section class="modal-section"><h3>注意事项</h3><p class="note-box">${recipe.notes}</p></section></div>`; }
function openModal(recipeId) { const recipe = recipes.find((item) => item.id === Number(recipeId)); if (!recipe) return; renderModal(recipe); modal.hidden = false; document.body.style.overflow = "hidden"; }
function closeModal() { modal.hidden = true; document.body.style.overflow = ""; }
function toggleFavorite(recipeId) { favoriteRecipeIds.has(recipeId) ? favoriteRecipeIds.delete(recipeId) : favoriteRecipeIds.add(recipeId); saveFavoriteRecipeIds(); renderRecipes(); }
function bindEvents() { searchInput.addEventListener("input", (event) => { state.query = event.target.value; renderRecipes(); }); categoryFilterButtons.forEach((button) => button.addEventListener("click", () => { state.category = button.dataset.category; categoryFilterButtons.forEach((item) => item.classList.toggle("active", item === button)); renderRecipes(); })); recipeGrid.addEventListener("click", (event) => { const favoriteButton = event.target.closest("[data-favorite-id]"); if (favoriteButton) { toggleFavorite(Number(favoriteButton.dataset.favoriteId)); return; } const card = event.target.closest("[data-card-recipe-id]"); if (card) openModal(card.dataset.cardRecipeId); }); favoriteFilter.addEventListener("click", () => { state.favoriteOnly = !state.favoriteOnly; favoriteFilter.classList.toggle("active", state.favoriteOnly); favoriteFilter.setAttribute("aria-pressed", String(state.favoriteOnly)); renderRecipes(); }); dailyRecommendation.addEventListener("click", (event) => { const target = event.target.closest("[data-recommend-id], .recommendation-image, .recommendation-title"); if (!target) return; const recommendId = target.dataset.recommendId || dailyRecommendation.querySelector("[data-recommend-id]")?.dataset.recommendId; if (recommendId) openModal(recommendId); }); disclaimerToggle.addEventListener("click", () => { const shouldExpand = disclaimerFullText.hidden; disclaimerFullText.hidden = !shouldExpand; disclaimerToggle.setAttribute("aria-expanded", String(shouldExpand)); }); modal.addEventListener("click", (event) => { if (event.target.matches("[data-close-modal]")) closeModal(); }); document.addEventListener("keydown", (event) => { if (event.key === "Escape" && !modal.hidden) closeModal(); }); }
bindEvents(); renderDailyRecommendation(); renderRecipes();
